<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Siswa_model extends CI_Model
{

    public $table = 'siswa';
    public $id = 'siswa_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
    //join tabel
    public function gabung($limit, $start){
        $this->db->select('*');
        $this->db->join('kelas', 'kelas.kelas_id = siswa.siswa_kelas_id');
        $this->db->join('kesehatan', 'kesehatan.kesehatan_id = siswa.siswa_kesehatan_id');
        $this->db->join('permasalahan', 'permasalahan.permasalahan_id = siswa.siswa_permasalahan_id');
        $this->db->join('psikologi', 'psikologi.psikologi_id = siswa.siswa_psikologi_id');
        $this->db->join('sosial', 'sosial.sosial_id = siswa.siswa_sosial_id');
        return $this->db->get('siswa', $limit, $start)->result();
    }

    public function gabung_kelas($limit, $start){
        $this->db->select('*');
        $this->db->join('kelas', 'kelas.kelas_id = siswa.siswa_kelas_id');
        return $this->db->get('siswa', $limit, $start)->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('*');
        $this->db->join('kelas', 'kelas.kelas_id = siswa.siswa_kelas_id');
        $this->db->join('kesehatan', 'kesehatan.kesehatan_id = siswa.siswa_kesehatan_id');
        $this->db->join('permasalahan', 'permasalahan.permasalahan_id = siswa.siswa_permasalahan_id');
        $this->db->join('psikologi', 'psikologi.psikologi_id = siswa.siswa_psikologi_id');
        $this->db->join('sosial', 'sosial.sosial_id = siswa.siswa_sosial_id');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('siswa_id', $q);
	$this->db->or_like('siswa_nis', $q);
	$this->db->or_like('siswa_nama', $q);
	$this->db->or_like('siswa_panggilan', $q);
	$this->db->or_like('siswa_gender', $q);
	$this->db->or_like('siswa_tgl_lahir', $q);
	$this->db->or_like('siswa_tempat_lahir', $q);
	$this->db->or_like('siswa_ortu', $q);
	$this->db->or_like('siswa_alamat', $q);
	$this->db->or_like('siswa_hp', $q);
	$this->db->or_like('siswa_agama', $q);
	$this->db->or_like('siswa_bahasa', $q);
	$this->db->or_like('siswa_tinggal', $q);
	$this->db->or_like('siswa_anak_ke', $q);
	$this->db->or_like('siswa_foto', $q);
	$this->db->or_like('siswa_kelas_id', $q);
	$this->db->or_like('siswa_kesehatan_id', $q);
	$this->db->or_like('siswa_permasalahan_id', $q);
	$this->db->or_like('siswa_psikologi_id', $q);
	$this->db->or_like('siswa_sosial_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('siswa_id', $q);
	$this->db->or_like('siswa_nis', $q);
	$this->db->or_like('siswa_nama', $q);
	$this->db->or_like('siswa_panggilan', $q);
	$this->db->or_like('siswa_gender', $q);
	$this->db->or_like('siswa_tgl_lahir', $q);
	$this->db->or_like('siswa_tempat_lahir', $q);
	$this->db->or_like('siswa_ortu', $q);
	$this->db->or_like('siswa_alamat', $q);
	$this->db->or_like('siswa_hp', $q);
	$this->db->or_like('siswa_agama', $q);
	$this->db->or_like('siswa_bahasa', $q);
	$this->db->or_like('siswa_tinggal', $q);
	$this->db->or_like('siswa_anak_ke', $q);
	$this->db->or_like('siswa_foto', $q);
	$this->db->or_like('siswa_kelas_id', $q);
	$this->db->or_like('siswa_kesehatan_id', $q);
	$this->db->or_like('siswa_permasalahan_id', $q);
	$this->db->or_like('siswa_psikologi_id', $q);
	$this->db->or_like('siswa_sosial_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    public function tampil_(){
        
        return $this->db->get_where('siswa', array(
            'siswa_kesehatan_id' => 1,
            'siswa_permasalahan_id' =>1,
            'siswa_psikologi_id' =>1,
            'siswa_sosial_id' =>1
        ));
        
    }

    // insert data
    public function insert($data)
    {
        return $this->db->insert('siswa', $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Siswa_model.php */
/* Location: ./application/models/Siswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-04 09:27:09 */
/* http://harviacode.com */
